#!/bin/bash

BORDER_ACTIVE_COLOR=0xff0076ff
BORDER_BACKGROUND_COLOR=0x000000

options=(
  style=round
  width=7.5
  hidpi=on
  active_color=$BORDER_ACTIVE_COLOR
  background_color=$BORDER_BACKGROUND_COLOR
  blacklist="Leader Key,CleanShot,Tuna"
)

borders "${options[@]}"
