schemaVersion = 1

[catalogs]
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'Tuna.EffectsCatalog'
    mode = 'none'
    selectedItemKeys = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'TunaEmoji.EmojiCatalog'
    mode = 'none'
    selectedItemKeys = []

[[comboMode.bindings]]
iconPath = 'camera.metering.center.weighted.average'
key = 'c'
label = 'Capture (Screenshot)'

    [[comboMode.bindings.children]]
    iconPath = 'document'
    key = 'c'
    label = 'to Clipboard'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252FAayush9029%252Fscreenshot%252Fcapture-to-clipboard/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = 'folder'
    key = 'd'
    label = 'to Download Folder'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252FAayush9029%252Fscreenshot%252Fcapture-area/Open%20URL'

[[comboMode.bindings]]
iconPath = 'magnifyingglass'
key = 's'
label = 'Search'

    [[comboMode.bindings.children]]
    iconPath = '/Applications/Brave Browser.app'
    key = 'b'
    label = 'Brave Bookmarks'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fbrowser-bookmarks%252Findex/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = 'face.smiling'
    key = 'e'
    label = 'Emoji'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Femoji-symbols%252Fsearch-emoji-symbols/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = 'apple.logo'
    key = 's'
    label = 'SF Symbols'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fjffrykkn%252Fsf-symbols-search%252Findex/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = 'square.3.layers.3d.down.right'
    key = 'w'
    label = 'Switch Windows (Tabs)'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fnavigation%252Fswitch-windows/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = '/Applications/Zen.app'
    key = 'z'
    label = 'Zen Bookmarks'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252FKeyruu%252Fzen-browser%252Fsearch-bookmarks/Open%20URL'

[[comboMode.bindings]]
iconPath = 'rectangle.grid.2x2'
key = 'w'
label = 'Aerospace'

    [[comboMode.bindings.children]]
    key = 'f'
    label = 'Fullscreen'
    url = 'tuna://run/text.aerospace%2520fullscreen/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    key = 'F'
    label = 'Flatten WS Tree'
    url = 'tuna://run/text.aerospace%2520flatten-workspace-tree/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    iconPath = 'app.connected.to.app.below.fill'
    key = 'j'
    label = 'Join with ...'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.left'
        key = 'h'
        label = 'Left'
        url = 'tuna://run/text.aerospace%2520join-with%2520left/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.down'
        key = 'j'
        label = 'Down'
        url = 'tuna://run/text.aerospace%2520join-with%2520down/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.up'
        key = 'k'
        label = 'Up'
        url = 'tuna://run/text.aerospace%2520join-with%2520up/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.right'
        key = 'l'
        label = 'Right'
        url = 'tuna://run/text.aerospace%2520join-with%2520right/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    iconPath = 'map'
    key = 'l'
    label = 'layout'

        [[comboMode.bindings.children.children]]
        iconPath = 'square.stack.3d.down.right'
        key = 'a'
        label = 'accordion'
        url = 'tuna://run/text.aerospace%2520layout%2520accordion%2520horizontal%2520vertical/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'pin'
        key = 'f'
        label = 'floating'
        url = 'tuna://run/text.aerospace%2520layout%2520floating%2520tiling/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'tablecells'
        key = 't'
        label = 'tiles'
        url = 'tuna://run/text.aerospace%2520layout%2520tiles%2520vertical%2520horizontal/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    key = 'm'
    label = 'Move Node to ...'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.left'
        key = 'h'
        label = 'Left'
        url = 'tuna://run/text.aerospace%2520move%2520left/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.down'
        key = 'j'
        label = 'Down'
        url = 'tuna://run/text.aerospace%2520move%2520down/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.up'
        key = 'k'
        label = 'Up'
        url = 'tuna://run/text.aerospace%2520move%2520up/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        iconPath = 'arrowshape.right'
        key = 'l'
        label = 'Right'
        url = 'tuna://run/text.aerospace%2520move%2520right/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        key = 'b'
        label = 'WS B'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520B/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        key = 'c'
        label = 'WS C'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520C/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        key = 'i'
        label = 'WS I'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520I/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        key = 'x'
        label = 'WS X'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520X/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    key = 'R'
    label = 'Reload config'
    url = 'tuna://run/text.aerospace%2520reload-config/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    key = 'b'
    label = 'Bring Node to ...'

        [[comboMode.bindings.children.children]]
        key = 'b'
        label = 'WS B'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520B%2520--focus-follows-window/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        key = 'c'
        label = 'WS C'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520C%2520--focus-follows-window/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        key = 'i'
        label = 'WS I'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520I%2520--focus-follows-window/Run%20Text%20as%20Shell%20Command'

        [[comboMode.bindings.children.children]]
        key = 'x'
        label = 'WS X'
        url = 'tuna://run/text.aerospace%2520move-node-to-workspace%2520X%2520--focus-follows-window/Run%20Text%20as%20Shell%20Command'

[[comboMode.bindings]]
iconPath = 'gamecontroller'
key = 'up'
label = '???'

    [[comboMode.bindings.children]]
    iconPath = 'gamecontroller'
    key = 'up'

        [[comboMode.bindings.children.children]]
        iconPath = 'gamecontroller'
        key = 'down'

            [[comboMode.bindings.children.children.children]]
            iconPath = 'gamecontroller'
            key = 'down'

                [[comboMode.bindings.children.children.children.children]]
                iconPath = 'gamecontroller'
                key = 'left'

                    [[comboMode.bindings.children.children.children.children.children]]
                    iconPath = 'gamecontroller'
                    key = 'right'

                        [[comboMode.bindings.children.children.children.children.children.children]]
                        iconPath = 'gamecontroller'
                        key = 'left'

                            [[comboMode.bindings.children.children.children.children.children.children.children]]
                            iconPath = 'gamecontroller'
                            key = 'right'

                                [[comboMode.bindings.children.children.children.children.children.children.children.children]]
                                iconPath = 'gamecontroller'
                                key = 'b'

                                    [[comboMode.bindings.children.children.children.children.children.children.children.children.children]]
                                    iconPath = 'party.popper'
                                    key = 'a'
                                    label = 'You found a secret!'
                                    url = 'tuna://run/url.raycast:%252F%252Fconfetti/Open%20URL'

[[comboMode.bindings]]
iconPath = 'gearshape'
key = ','
label = 'Settings'

    [[comboMode.bindings.children]]
    key = ','
    label = 'system-settings'
    url = 'tuna://run/TunaCore.ApplicationsCatalog.System%20Settings/TunaCore.CommonActionsCatalog.Open'

    [[comboMode.bindings.children]]
    iconPath = 'power'
    key = 'd'
    label = 'Shut Down'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fsystem%252Fshut-down/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = 'lock'
    key = 'l'
    label = 'lock-screen'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fsystem%252Flock-screen/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = 'restart'
    key = 'r'
    label = 'restart'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fsystem%252Frestart/Open%20URL'

    [[comboMode.bindings.children]]
    iconPath = 'powersleep'
    key = 's'
    label = 'sleep'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fsystem%252Fsleep/Open%20URL'

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 1
    carbonModifiers = 6912

    [hotkeys.app.comboMode]
    carbonKeyCode = 49
    carbonModifiers = 6912

    [hotkeys.app.dictation]
    carbonKeyCode = 2
    carbonModifiers = 6912

    [hotkeys.app.textMode]
    carbonKeyCode = 17
    carbonModifiers = 6912

[settings]
comboModeCheatsheetDelayMS = 0
physicalHyperKeySource = 'capsLock'
themeIdentifier = 'com.brnbw.tuna.themes.default'